//
//  AIABadgeView.swift
//  Components
//
//  Created by Duc Nguyen on 21/4/25.
//  Copyright © 2025 BlueBelt. All rights reserved.
//

import UIKit
import SnapKit

/// Any configuration after this view was added to superview won't have any effect
public class AIABadgeView: UIView {
    public var minimumSize: CGFloat = 12
    public var content: String { didSet { contentChanged() } }
    private var contentFont: UIFont = .appFont(\.subText3SBUpCase)
    private var contentColor: UIColor = .clear
    /// This will make a hole in the current view as the content is masked
    public var clippingTargetView: UIView
    
    public init(content: String = "", clippingTargetView: UIView) {
        self.content = content
        self.clippingTargetView = clippingTargetView
        super.init(frame: .zero)
    }
    
    @available(iOS, unavailable)
    required init?(coder: NSCoder) { fatalError("Unsupported") }
    
    public override func didMoveToSuperview() {
        super.didMoveToSuperview()
        guard superview != nil else { return }
        updateSizeConstraint()
    }
    
    public override func layoutSubviews() {
        super.layoutSubviews()
        clipsToBounds = true
        layer.cornerRadius = min(bounds.width, bounds.height) / 2
        contentChanged()
    }
    
    func contentChanged() {
        if content.isEmpty {
            isHidden = true
            glyphMaskLayer.removeFromSuperlayer()
            targetViewLayer.removeFromSuperlayer()
        } else {
            isHidden = false
            updateSizeConstraint()
            applyGlyphMask()
            applyMaskingForTargetView()
        }
    }
    
    var glyphMaskLayer = CAShapeLayer()
    
    // This code was generated by ChatGPT and is working flawlessly
    private func applyGlyphMask() {
        glyphMaskLayer.removeFromSuperlayer()
        glyphMaskLayer = CAShapeLayer()
        let path = UIBezierPath(rect: bounds)
        
        // Create attributed string
        let attributedString = NSAttributedString(string: content, attributes: [
            .font: contentFont
        ])
        
        // Create text path
        let textPath = CGMutablePath()
        let line = CTLineCreateWithAttributedString(attributedString)
        
        // Get line bounds for centering
        var ascent: CGFloat = 0
        var descent: CGFloat = 0
        var leading: CGFloat = 0
        let lineWidth = CGFloat(CTLineGetTypographicBounds(line, &ascent, &descent, &leading))
        let lineHeight = ascent + descent
        
        let lineOffset = CGPoint(
            x: (bounds.width - lineWidth) / 2,
            y: (bounds.height - lineHeight) / 2 + descent
        )
        
        // Draw each run
        let runArray = CTLineGetGlyphRuns(line) as NSArray
        for runIndex in 0..<runArray.count {
            let run = runArray[runIndex] as! CTRun
            let runFont = (CTRunGetAttributes(run) as NSDictionary)[kCTFontAttributeName] as! CTFont
            let glyphCount = CTRunGetGlyphCount(run)
            
            for glyphIndex in 0..<glyphCount {
                var glyph = CGGlyph()
                var position = CGPoint()
                CTRunGetGlyphs(run, CFRangeMake(glyphIndex, 1), &glyph)
                CTRunGetPositions(run, CFRangeMake(glyphIndex, 1), &position)
                
                if let glyphPath = CTFontCreatePathForGlyph(runFont, glyph, nil) {
                    let t = CGAffineTransform(
                        translationX: position.x + lineOffset.x,
                        y: position.y + lineOffset.y
                    )
                    textPath.addPath(glyphPath, transform: t)
                }
            }
        }
        var flip = CGAffineTransform(scaleX: 1, y: -1)
        flip = flip.translatedBy(x: 0, y: -bounds.height)
        
        let flippedTextPath = textPath.copy(using: &flip) ?? textPath
        path.append(UIBezierPath(cgPath: flippedTextPath))
        glyphMaskLayer.path = path.cgPath
        glyphMaskLayer.fillRule = .evenOdd
        layer.mask = glyphMaskLayer
    }
    
    var targetViewLayer = CAShapeLayer()
    
    private func applyMaskingForTargetView() {
        targetViewLayer.removeFromSuperlayer()
        // Remove old mask layer if any
        
        targetViewLayer = CAShapeLayer()

        // Create the hole frame with padding
        let cornerRadius = bounds.height / 2 + 1
        let bounds = clippingTargetView.bounds
        let path = UIBezierPath()
        var currentPoint = bounds.origin
        path.move(to: currentPoint)
        currentPoint.x = currentPoint.x + bounds.width - self.bounds.width / 2 - 1
        path.addLine(to: currentPoint)
        path.addArc(
            withCenter: .init(x: currentPoint.x + cornerRadius, y: currentPoint.y),
            radius: cornerRadius, startAngle: .pi, endAngle: .pi / 2, clockwise: false
        )
        currentPoint = .init(x: bounds.maxX, y: currentPoint.y + cornerRadius)
        path.addLine(to: currentPoint)
        currentPoint = .init(x: bounds.maxX, y: bounds.maxY)
        path.addLine(to: currentPoint)
        currentPoint = .init(x: bounds.minX, y: bounds.maxY)
        path.addLine(to: currentPoint)
        path.close()
        
        targetViewLayer.path = path.cgPath
        targetViewLayer.fillRule = .evenOdd
        targetViewLayer.frame = clippingTargetView.bounds
        
        // 🎯 Clip the view to correct shape, leaving the remaining part transparent
        clippingTargetView.layer.mask = targetViewLayer
    }
    
    /// Update badge size with padding
    private func updateSizeConstraint() {
        let expectedTextWidth = (content as NSString).size(withAttributes: [.font: contentFont]).width
        let finalWidth = max(expectedTextWidth + 8, minimumSize) // Add some padding
        snp.remakeConstraints {
            $0.width.greaterThanOrEqualTo(finalWidth)
            $0.height.greaterThanOrEqualTo(minimumSize)
            guard let superview else { return }
            $0.centerX.equalTo(superview.snp.trailing)
            $0.centerY.equalTo(superview.snp.top)
        }
    }
}
